### ISSUE TITLE
Comparing to https://github.com/dnaeon/go-vcr

### ISSUE THREAD

**Issue by abourget** [seborama/govcr#25]
Hi Seb,

I was wondering if you've read through https://github.com/dnaeon/go-vcr and the reason why you chose to write your own ?

I'm currently choosing a solution, and I'd hugely appreciate your insight on the design of both.

thanks!

**Comment by seborama** [comment]
Hi,

Thanks for your interest.

I started `govcr` as a personal project to practice Go last year. At the time, Google had little to say about Go and VCR in search results, with most pointing at PHP VCR.

When it became useful to me, I thought it might also be to someone else.

I haven't looked at Marin's `go-vcr` until now. It seems we are following the same design principles (decoration of http.Client RoundTripper interface), with some minor differences in the implementation. This is the more flexible approach and also the simplest so it's a developer's win-win.

govcr attempts to replay the HTTP transfer as it originally occurred (based on the original data structures), including HTTP errors. It also has a concept of hooks to help deal with dynamic data (such as request IDs or Timestamps) which would otherwise not match when replaying.

Marin's `go-vcr` does have over 100 stars which is a token that it does its job pretty well. This is worth considering too!

Good luck with your decision!
Seb
